### ISSUE TITLE
Incompatible with Haxe 3.3.0-RC1

### ISSUE THREAD

**Issue by anissen** [underscorediscovery/luxe#383]
Trying to compile with the newly released Haxe 3.3.0-RC1, I get the following compilation error:

``` bash
(...)/snow/snow/types/Types.hx:72: characters 25-38 : Type not found : UserConfigDef
```

**Comment by underscorediscovery** [comment]
Yep, they made breaking changes. I will fix it soon.

**Comment by ntrf** [comment]
@underscorediscovery Are you sure YOU need to fix it? It looks like a bug on their side. Niether build macro, nor `MacroType` are capable of accessing struct types with `Context.getType`. Compiler just crashes.

**Comment by anissen** [comment]
Luxe is compatible with Haxe 3.4.0.
